kind: pipeline
steps:
- name: Unit testing
  image: maven:3-jdk-11
  commands:
  - mvn package
  - mvn test

- name: Build-master
  image: maven:3-jdk-11
  commands:
    - mvn -f pom.xml -Dspring.profiles.active=master package
  when:
    branch:
      - master
- name: Server-master
  image: alpine
  commands:
    - cd /target/
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war master.war
    - curl -v -u admin:admin -T master.war 'http://25.2.28.209:8085/manager/text/deploy?path=/master&update=true'
  when:
    branch:
      - master

- name: Build-dev
  image: maven:3-jdk-11
  commands:
    - mvn -f pom.xml -Dspring.profiles.active=dev package
  when:
    branch:
      - dev
- name: Server-dev
  image: alpine
  commands:
    - cd /target/
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war dev.war
    - curl -v -u admin:admin -T dev.war 'http://25.2.28.209:8085/manager/text/deploy?path=/dev&update=true'
  when:
    branch:
      - dev

- name: notify
  image: drillster/drone-email
  settings:
    from: dubon181014@unis.edu.gt
    host: smtp.gmail.com
    port: 465
    username:
       from_secret: usuario
    password: 
      from_secret: contra

    recipients:
        - evelyndubon@gmail.com

  when:
    status:
    - success
    - failure

