kind: pipeline


steps:
- name: Unit testing
  image: maven:3-jdk-11
  commands:
  - mvn package
  - mvn test
- name: SonarQube
  image: maven:3-jdk-11
  commands: 
    - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=hola -Dsonar.host.url=http://de78-2800-98-1127-192c-1850-15f0-b2ce-ef53.ngrok.io

  
